name: Deploy to AWS ECS

on:
  push:
    branches: [main]

env:
  AWS_REGION: eu-central-1
  TABLE_NAME: timeStampsTable-0d0843b
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        mask-password: true

    - name: Build Docker image
      working-directory: ./backend
      run: |
        docker build -t show-time-backend .
        docker tag show-time-backend:latest ${{ steps.login-ecr.outputs.registry }}/show-time-backend-e5376fb:latest

    - name: Push to Amazon ECR
      run: |
        docker push ${{ steps.login-ecr.outputs.registry }}/show-time-backend-e5376fb:latest

    - name: Deploy to ECS
      uses: aws-actions/amazon-ecs-deploy@v1
      with:
        service: ecs-service-2f3c311
        cluster: show-time-cluster
        task-definition: arn:aws:ecs:eu-central-1:241661649400:task-definition/show-time-task:1
        wait-for-service-stability: true

    - name: Debug environment
      run: env

    - name: Debug current directory
      run: pwd && ls -la

    # Example of a step that might fail
    - name: Build Docker image
      run: docker build -t my-image .
      # Add 'continue-on-error: true' to keep logs if needed

    # Add similar debug info for other failing steps
